-- AlterTable
ALTER TABLE "Booking" ALTER COLUMN "checkInDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "checkInDate" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "checkOutDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "checkOutDate" SET DATA TYPE TIMESTAMP(3);
